spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:cruddb}
      username: ${MONGO_USERNAME:}
      password: ${MONGO_PASSWORD:}
  
server:
  port: ${SERVER_PORT:8080}
